# Generated by Django 3.0.7 on 2020-06-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
